[default]
SQLALCHEMY_TRACK_MODIFICATIONS=false

[development]
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:root@localhost:3306/flask_store"

[production]
SQLALCHEMY_DATABASE_URI = "postgresql://postgres:docker@localhost/flask_store"

[testing]
SQLALCHEMY_DATABASE_URI = "sqlite://"
